### ISSUE TITLE
Unavailable Singularity Containers

### ISSUE THREAD

**Issue by KrisDavie** [dynverse/dynmethods#148]
It seems like some of the ti singularity containers are unavailable from Singularity Hub because of build issues.

The containers are as follows:

dynverse/ti_celltree_gibbs
dynverse/ti_celltree_maptpx
dynverse/ti_celltree_vem
dynverse/ti_fateid
dynverse/ti_monocle_ica
dynverse/ti_monocle_ddrtree
dynverse/ti_projected_monocle
dynverse/ti_projected_tscan
dynverse/ti_raceid_stemid
dynverse/ti_sincell
dynverse/ti_slicer
dynverse/ti_tscan
dynverse/ti_waterfall
dynverse/ti_paga

Cheers,
Kris

**Comment by rcannood** [comment]
Thanks Kris! I'm taking a look at it.

**Comment by rcannood** [comment]
I performed manual build triggers on each of the containers, they should be working now. Can you confirm this?

**Comment by KrisDavie** [comment]
Seems like most of them are present now, with three exceptions.

ti_paga is still not there (wasn't before either)

ti_slingshot and ti_projected_slingshot are not there now (but were before)

Cheers

**Comment by rcannood** [comment]
Paga is also fixed now :)

For some reason, the singularity build of slingshot is failing whereas
docker is working fine:
https://travis-ci.org/dynverse/ti_slingshot/builds/479990234

I'll keep you up to date

**Comment by rcannood** [comment]
The Slingshot and Projected Slingshot Singularity containers have also finished building :) Can you confirm everything is working now?

Side note, @zouter is working on updating [babelwhale](github.com/dynverse/babelwhale) to Singularity 3.0. With it, at some point, we will probably switch from singularity hub (which seems on their way to being deprecated) to the [Sylabs Singularity Library](https://cloud.sylabs.io/library).

**Comment by zouter** [comment]
It works for me, :+1: @rcannood !

**Comment by zouter** [comment]
This is fixed now I think... And will probably no longer be an issue once we start to depend on singularity 3!
